# GENERAL
n_seeds: 5
num_workers: 1

# MODEL
classifier: "linear"
backbone: "resnet18"

# DATA SETUP
scenario: 'minidomainnet'
task_incr: False
iterations_per_task: 300 # Instead of epochs to balance compute

# STRATEGY
strategy: "EWC"
lr:
#  - 0.1
  - 0.01
#  - 0.001
#  - 0.0001
iw_strength:
#  - 0.1
  - 1
#  - 10
#  - 100
#  - 1000
bs:
  - 128

# CONTINUAL EVAL
enable_continual_eval: True
eval_periodicity: 1
eval_task_subset_size: 1000